### PR TITLE
Changed file encoding from windows-1252 to utf-8

### PR DESCRIPTION
**Pull request by AykutCevik**
The encoding of this file led to an error in Magento while adding this module. I've changed the encoding to UTF-8 which has fixed the issue.

### CODE REVIEW

**Comment by Dnd-Gimix** [comment]
Hello @AykutCevik ,

First, thank you for using and contributing to PIMGento2 (API) !
Good call on the encoding of the file, we will review your changes and integrate them.

Thanks again.

**Comment by Dnd-Gimix** [comment]
@AykutCevik ,

Thank you for your contribution, your changes have been integrated.
Have a nice day !

Regards,

**Comment by Dnd-Gimix** [comment]
Hi @sydekumf , @AykutCevik 

New release 100.1.1 is out !

Have a nice day.

Regards,

**Comment by cbarbe** [comment]
Hello @AykutCevik ,
My name is Charles, I'm part of the Marketplace team at Akeneo, taking care of the Akeneo ecosystem.
I'm very glad to announce that Akeneo has partnered with Dnd to take over the PIMGento 2 API module! It is now the official Akeneo Connector for Magento 2.
For this collaboration to happen, we are moving Intellectual Property and all Github commits to Akeneo official Github account.
As a result, we'd be very interested in including your contribution to our new Product.
Could you please fill in the short form here, to give us the rights to use it?
https://www.akeneo.com/contributor-license-agreement/

Many thanks in advance for your help, and again THANK YOU for contributing to Akeneo/Magento ecosystem on behalf of the whole team here :)

Best regards, feel free to send me a PM for more info: marketplace@akeneo.com
Charles

**Pull request merged**
