### PR TITLE
Added website mapping by akeneo Attribute as feature

### PR DESCRIPTION
**Pull request by JelleGroenendal**
Added feature to select website by Akeneo attribute

#41 , #57

### CODE REVIEW

**Comment by sydekumf** [comment]
Thanks for the PR. Can you please describe an example how the published website attribtue should look like? It is hard to understand how that should work. Also in line 1152 you have an undefined variable `tmpProductTable` :-)

**Comment by JelleGroenendal** [comment]
basically what this does is emptying the catalog_product_website table for all products that are imported.
Then it gets what is checked in the published_on_website attribute Akeneo and loops trough that.
If its checked it creates a entry based on what you have configured in Pimgento2 config.

**Comment by sydekumf** [comment]
So it is an Akeneo attribute or Magento attribute?

**Comment by JelleGroenendal** [comment]
look in /doc/important_stuff/how_to.md

**Comment by sydekumf** [comment]
I don't understand why you can not use the channel/website mapping for that? If the product is assigned to a channel in Akeneo, and the channel is mapped to the website in Magento, that's the point where the product should be assigned to the website, shouldn't it?

**Comment by JelleGroenendal** [comment]
The changes i created were based on 1 channel. In our situation we only have 1 channel.

**Comment by sydekumf** [comment]
So as far as I understand the code:
- You have to create a multiselect attribute in Akeneo and fill in the channel names there, you want the product belong to
- On Magento side you insert a mapping channel to website

If a product gets imported with the Akeneo attribute set to "channel-ecommerce" it gets the website by the website/channel mapping. Is this right?

But then again: Why don't you use the usual channel assignment of Akeneo?

**Comment by JelleGroenendal** [comment]
It might be good to know but we are on enterprise akeneo that means we are limited on amount of channels.

**Comment by sydekumf** [comment]
Okay, I will give it a try :-) Do you know when this PR will be merged? :-) Thanks!

**Comment by JelleGroenendal** [comment]
I assumed that somewhere in the tmp product table the channel would exist but this is not the case. Because of that the channel based mapping is a bit more difficult to create. However i do believe the fix i provided for mapping by attribute is also valid as a solution for other cases.  I will look in to if i can add the channels in the tmp product table tomorrow. Not sure if this is easy if it is then i will fix this tomorrow.

**Comment by sydekumf** [comment]
One further hint: In line 1098 you compare a Magento store code with a website code?
`if ($magentoStore->getCode() == $site['website']) {`

**Comment by sydekumf** [comment]
Can you say when this PR will be merged into master?

**Comment by JelleGroenendal** [comment]
Whel @magentix or @Dnd-Gimix would have to look in to it first i believe. I'm only contributing but i hope soon. In addition i have another PR that has been open for close to a month now i hope this one will go faster.

**Comment by Dnd-Gimix** [comment]
Hello @JelleGroenendal , @sydekumf ,

We have fixed the website assignation on the new 100.2.1 version of the connector.
Now, PIMGento 2 API will only assign products to the configured websites in the channel mapping configuration.

Also, you'll find a new configuration to assign the channel you want to retrieve values from for the admin website : you'll need to fill this configuration in order to launch your imports.

Could you test this new version and come back to us to confirm that everything is now working well ?
If the new version fix the issue, I'll close this PR.

Have a good day !

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @sydekumf  , @JelleGroenendal ,

Have you been able to test the new release that fix product website assignation ?

Regards,

**Comment by JelleGroenendal** [comment]
I cant test this on our environment considering the issues we have with the amount of attributes problem.
I would have to setup a new Akeneo environment without our current product portfolio. 
We currently are running on a altered Pimgento because of this and several other problems.

**Comment by Dnd-Gimix** [comment]
Hello @JelleGroenendal ,

As this feature has already been developed by our team, this PR won't be integrated to the repository.
Feel free to come back to us in this issue to confirm that product website assignation is working well for you : https://github.com/Agence-DnD/PIMGento-2-API/issues/57

Thank you for the active contribution.
Have a good day !

Regards,

**Pull request closed without merging**
